# Define an array of symbolic link sources and targets
$(pwd)/zsh/.zshrc:$HOME/.zshrc
$(pwd)/zsh/.zshenv:$HOME/.zshenv
$(pwd)/zsh/.zprofile:$HOME/.zprofile
$(pwd)/pi/agent/themes:$HOME/.pi/agent/themes
$(pwd)/pi/agent/settings.json:$HOME/.pi/agent/settings.json
$(pwd)/pi/agent/keybindings.json:$HOME/.pi/agent/keybindings.json
