#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
SKETCHY_SCRIPT_DIR="$CONFIG_DIR/scripts"

# Load global styles, colors and icons
source "$CONFIG_DIR/globalstyles.sh"

POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"
POPUP_OFF="sketchybar --set \$NAME popup.drawing=off"

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace_modes.sh"
source "$ITEM_DIR/spaces.sh"

# source "$ITEM_DIR/spacer.sh" 3 left


# Notch

# Right
source "$ITEM_DIR/datetime.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/diskmonitor.sh"

source "$ITEM_DIR/spacer.sh" 2 right

# source "$ITEM_DIR/weather.sh" right
source "$ITEM_DIR/github_prs.sh" right

source "$ITEM_DIR/spacer.sh" 4 right

# Brackets '/space\..*/'
sketchybar --add bracket left.side '/space\..*/'                                                 \
                                                                                                 \
           --add bracket notifications                                                           \
           --set notifications "${bracket_defaults[@]}"                                          \
                                                                                                 \
           --add bracket status_icons diskmonitor volume_icon volume wifi datetime battery \
           --set status_icons "${bracket_defaults[@]}"

sketchybar --hotload on
sketchybar --update
