[theme]
name = "cyberpunk-theme"
parent = "default"

[colors]
AlertInfo = "#72F6B2"
AlertWarn = "#ff966c"
AlertError = '#ED7892'
Annotation = '#DDAFF8'
Base = '#c8d3f5'
Guidance = '#95C9F8'
Important = '#00FF9C'
Title = '#82aaff'
Muted = '#828bb8'
SyntaxComment = '#636da6'
