return {
  'folke/trouble.nvim',
  opts = {
    modes = {
      lsp = {
        win = { position = 'right' },
      },
    },
    keys = {
      ['?'] = 'help',
      r = 'refresh',
      R = 'toggle_refresh',
      q = 'close',
      o = 'jump_close',
      ['<esc>'] = 'cancel',
      ['<cr>'] = 'jump',
      ['<2-leftmouse>'] = 'jump',
      ['<c-s>'] = 'jump_split',
      ['<c-v>'] = 'jump_vsplit',
      -- go down to next item (accepts count)
      -- j = "next",
      ['}'] = 'next',
      [']]'] = 'next',
      -- go up to prev item (accepts count)
      -- k = "prev",
      ['{'] = 'prev',
      ['[['] = 'prev',
      dd = 'delete',
      d = { action = 'delete', mode = 'v' },
      i = 'inspect',
      p = 'preview',
      P = 'toggle_preview',
      zo = 'fold_open',
      zO = 'fold_open_recursive',
      zc = 'fold_close',
      zC = 'fold_close_recursive',
      ['<space>'] = 'fold_toggle',
      zA = 'fold_toggle_recursive',
      zm = 'fold_more',
      zM = 'fold_close_all',
      zr = 'fold_reduce',
      zR = 'fold_open_all',
      zx = 'fold_update',
      zX = 'fold_update_all',
      zn = 'fold_disable',
      zN = 'fold_enable',
      zi = 'fold_toggle_enable',
    },
  },
  cmd = 'Trouble',
  keys = {
    {
      '<leader>td',
      '<cmd>Trouble diagnostics toggle<cr>',
      { desc = '[T]rouble [D]iagnostic', silent = true, noremap = true },
    },
    {
      '<leader>tl',
      '<cmd>Trouble lsp toggle focus=false win.position=right<cr>',
      {
        desc = '[T]rouble [L]sp toggle',
        silent = true,
        noremap = true,
      },
    },
    {
      '<leader>ts',
      '<cmd>Trouble symbols toggle focus=false<cr>',
      {
        desc = '[T]rouble [S]ymbol toggle',
        silent = true,
        noremap = true,
      },
    },
    {
      '<leader>qf',
      '<cmd>Trouble qflist open focus=true win.position=right<cr>',
      {
        desc = '[Q]uick [F]ix list toggle',
        silent = true,
        noremap = true,
      },
    },
  },
}
